/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Edge functions do Supabase NUNCA devem ser cacheadas
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co'),
  new NetworkOnly()
);

// Permite que o app dispare skipWaiting via postMessage
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Recebe push da edge function e exibe notificação
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'Higi$Controle';
    const options: NotificationOptions = {
      body: data.body,
      icon: data.icon || '/android-chrome-192x192.png',
      badge: data.badge || '/favicon-32x32.png',
      data: data.data || {},
      vibrate: [200, 100, 200],
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (e) {
    console.error('Error parsing push data', e);
  }
});

// Ao clicar na notificação, abre o app
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const path = event.notification.data?.url || '/';
  // Usa o scope do SW para montar URL correta (funciona em localhost e produção)
  const scope = self.registration.scope;
  const fullUrl = scope.endsWith('/') 
    ? scope + path.replace(/^\//, '')
    : scope + path;

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // Se já tem uma janela do app aberta, foca e navega para a rota
        for (const client of windowClients) {
          if (client.url.startsWith(scope) && 'focus' in client) {
            client.focus();
            // Envia mensagem para o React Router navegar
            client.postMessage({ type: 'NAVIGATE', url: path });
            return;
          }
        }
        // Se não tem janela aberta, abre o app na URL correta
        if (self.clients.openWindow) {
          return self.clients.openWindow(fullUrl);
        }
      })
  );
});